version: '3.8'

services:
  geekshopping_message_bus:
    build:
      context: ./GeekShopping.MessageBus

  geekshopping_identity_server:
    build:
      context: ./GeekShopping.IdentityServer
    depends_on:
      - geekshopping_web_frontend

  geekshopping_products_api:
    build:
      context: ./GeekShopping.ProductAPI
    depends_on:
      - products_db

  geekshopping_cart_api:
    build:
      context: ./GeekShopping.CartAPI
    depends_on:
      - cart_db

  geekshopping_coupon_api:
    build:
      context: ./GeekShopping.CouponAPI
    depends_on:
      - coupon_db

  geekshopping_order_api:
    build:
      context: ./GeekShopping.OrderAPI
    depends_on:
      - order_db
      - geekshopping_message_bus

  geekshopping_web_frontend:
    build:
      context: ./GeekShopping.Web
    depends_on:
      - geekshopping_products_api
      - geekshopping_cart_api

  products_db:
    image: "mysql:latest"

  cart_db:
    image: "mysql:latest"
    
  coupon_db:
    image: "mysql:latest"

  order_db:
    image: "mysql:latest"

  identity_server_db:
    image: "mysql:latest"

  geek_shopping_rabbitmq:
    image: rabbitmq:3.11.9-management-alpine