version: '3.8'

services:
  geekshopping_identity_server:
    build:
      context: .
      dockerfile: ./GeekShopping.IdentityServer/Dockerfile
    depends_on:
      - identity_server_db

  geekshopping_products_api:
    build:
      context: .
      dockerfile: ./GeekShopping.ProductAPI/Dockerfile
    depends_on:
      - products_db

  geekshopping_cart_api:
    build:
      context: .
      dockerfile: ./GeekShopping.CartAPI/Dockerfile
    depends_on:
      - cart_db

  geekshopping_coupon_api:
    build:
      context: .
      dockerfile: ./GeekShopping.CouponAPI/Dockerfile
    depends_on:
      - coupon_db

  geekshopping_order_api:
    build:
      context: .
      dockerfile: ./GeekShopping.OrderAPI/Dockerfile
    depends_on:
      - order_db

  geekshopping_email:
    build:
      context: .
      dockerfile: ./GeekShopping.Email/Dockerfile
    depends_on:
      - email_db

  geekshopping_payment_api:
    build:
      context: .
      dockerfile: ./GeekShopping.PaymentAPI/Dockerfile

  geekshopping_api_gateway:
    build:
      context: .
      dockerfile: ./GeekShopping.APIGateway/Dockerfile
    depends_on:
      - geekshopping_products_api
      - geekshopping_cart_api
      - geekshopping_coupon_api
      - geekshopping_order_api
      - geekshopping_payment_api
      - geekshopping_email
      - geekshopping_identity_server

  geekshopping_web_frontend:
    build:
      context: .
      dockerfile: ./GeekShopping.Web/Dockerfile
    depends_on:
      - geekshopping_products_api
      - geekshopping_cart_api

  products_db:
    image: "mysql:latest"

  cart_db:
    image: "mysql:latest"
    
  coupon_db:
    image: "mysql:latest"

  order_db:
    image: "mysql:latest"

  identity_server_db:
    image: "mysql:latest"

  email_db:
    image: "mysql:latest"

  geek_shopping_rabbitmq:
    image: rabbitmq:3.11.9-management-alpine