version: '3.8'

services:

  geekshopping_identity_server:
    build:
      context: ./GeekShopping.IdentityServer
      dockerfile: Dockerfile
    depends_on:
      - geekshopping_web_frontend

  geekshopping_products_api:
    build:
      context: ./GeekShopping.ProductAPI
      dockerfile: Dockerfile
    depends_on:
      - products_db

  geekshopping_cart_api:
    build:
      context: ./GeekShopping.CartAPI
      dockerfile: Dockerfile
    depends_on:
      - cart_db

  geekshopping_web_frontend:
    build:
      context: ./GeekShopping.Web
      dockerfile: Dockerfile
    depends_on:
      - geekshopping_products_api
      - geekshopping_cart_api

  products_db:
    image: "mysql:latest"

  cart_db:
    image: "mysql:latest"
    
  identity_server_db:
    image: "mysql:latest"